### ISSUE TITLE
Data curation

### ISSUE THREAD

**Issue by dig-singh** [goyergeek/Weather-Project#3]
Hi..
We are looking to work on data curation of NCDC data.
You have done some thing good in this area.

Is there any thing related to data curation done by you in this project which can help us??

Or could you please explain basic objective of your application.

Thanks in advance
dig-singh

**Comment by goyergeek** [comment]
Hi..
It has been a while since I have looked at this project.  I moved away from it for a while to work on my node and express skills.  The NCDC datasets are somewhat of a challenge to navigate, and the very basic documentation they provide on their site will help you pick it apart, but will not give you a good idea of how the datasets are truly organised.  I primarily used Postman Rest Client for Chrome to start digging into the NCDC data.  

My next steps in this project, which I will re-engage on sometime in the spring, will be to build an application that provides a detailed overview of how the NCDC data is organised to help in writing meaningful queries. 

The basic objective of this application is to retrieve and store local temperature data from various observation stations, and provide light analysis of that data in the form of trending graphs, sparknotes, and other analytic data visualizations.  There are intended expansions to this basic functionality, including analytics involving ocean surface temperatures, but this is still just an idea and nothing firm has been done.

I would be more than happy to assist per my availability.
